version: "3.1"
services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: device-management
        volumes:
            - ./:/var/www/html

    webserver:
        image: nginx:1.17.10
        container_name: device-management-nginx
        links:
            - php:fpm
        environment:
            - FPM_HOST=fpm
            - FPM_PORT=9000
        volumes:
            - ./:/var/www/html
            - ./docker/nginx_conf:/etc/nginx/conf.d/
        ports:
            - "8080:80"

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: device-management-mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: device-management-php
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
        ports:
            - 3306:3306

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     links:
    #         - db:mysql
    #     ports:
    #         - "8088:80"
    #     environment:
    #         - PMA_HOSTS=mysql
    #         - PMA_PORT=3307
    #         - PMA_USER=admin
    #         - PMA_PASSWORD=secret
